"""Synthetic sentinel values used by the Phase 1A harness."""

GATEWAY_SENTINEL = "PANKSTER_SENTINEL_GATEWAY_A7F1"
ROOT_SENTINEL = "PANKSTER_SENTINEL_ROOT_B8E2"
PROFILE_A_SENTINEL = "PANKSTER_SENTINEL_PROFILE_A_C9D3"
PROFILE_B_SENTINEL = "PANKSTER_SENTINEL_PROFILE_B_D0E4"
MCP_SENTINEL = "PANKSTER_SENTINEL_MCP_E1F5"
OAUTH_SENTINEL = "PANKSTER_SENTINEL_OAUTH_F2A6"

ALL_SENTINELS = (
    GATEWAY_SENTINEL,
    ROOT_SENTINEL,
    PROFILE_A_SENTINEL,
    PROFILE_B_SENTINEL,
    MCP_SENTINEL,
    OAUTH_SENTINEL,
)

REDACTED_SENTINEL = "[REDACTED_SENTINEL]"


def contains_sentinel(value: object) -> bool:
    text = str(value)
    return any(sentinel in text for sentinel in ALL_SENTINELS)
