"use client";
import {useEffect,useState} from "react";
import {formatDate,formatMoney} from "@/lib/format";
import type {PaymentChainSummary} from "@/lib/finance/paymentChains";
import type {PaymentChainSeed} from "./PaymentChainModal";
import {Card,CardContent} from "@/components/ui/Card";
export function PaymentChainList({onOpen,version=0}:{onOpen:(seed:PaymentChainSeed)=>void;version?:number}) {
 const [chains,setChains]=useState<PaymentChainSummary[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [search,setSearch]=useState('');const [refresh,setRefresh]=useState(0);
 useEffect(()=>{let cancelled=false;setLoading(true);fetch('/api/finance/companies?resource=payment-chain-index',{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error??'Ошибка загрузки');return b.chains as PaymentChainSummary[];}).then(rows=>{if(!cancelled){setChains(rows);setError('');}}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[refresh,version]);
 return <Card><CardContent className="space-y-4 pt-5"><h2 className="font-semibold">Операции с разбивкой</h2><p className="text-sm text-slate-600">Выберите исходную операцию: все её части и даты показаны внутри карточки. Здесь видны операции за весь период.</p><div className="flex flex-col gap-2 sm:flex-row"><input aria-label="Поиск исходной суммы" placeholder="Название или исходная сумма, например 55000" value={search} onChange={e=>setSearch(e.target.value)} className="min-h-11 min-w-0 flex-1 rounded-lg border border-slate-300 px-3"/><button type="button" onClick={()=>setRefresh(n=>n+1)} className="min-h-11 rounded-lg border px-3">Обновить список</button></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{loading?<p>Загружаю исходные суммы…</p>:<div className="space-y-3">{chains.filter(c=>(c.label+' '+c.amount).toLowerCase().includes(search.toLowerCase().replace(/\s/g,''))||c.label.toLowerCase().includes(search.toLowerCase())).map(c=><button key={c.id} type="button" onClick={()=>onOpen(c.chainId?{chainId:c.chainId}:{paymentId:c.paymentId})} className="block min-h-11 w-full rounded-xl border border-slate-200 p-4 text-left hover:bg-violet-50"><div className="flex flex-wrap items-center justify-between gap-2"><b>{c.amount===null?'Исходная сумма неизвестна':formatMoney(c.amount)}</b><span className="text-sm text-violet-700">{c.count} частей · {c.status==='cancelled'?'Отменено':c.revision?'Версия '+c.revision:'Из выписки'}</span></div><p className="mt-1 break-anywhere text-sm">{c.label}</p><p className="mt-2 text-xs text-slate-500">Источник {formatDate(c.date)} · расходы до {formatDate(c.lastDate)} · открыть операцию →</p></button>)}{!chains.length&&<p className="text-sm text-slate-500">Разбитых операций пока нет. Нажмите «Разбить» у расхода в реестре или на проверке выписки.</p>}</div>}</CardContent></Card>;
}
