"use client";

import { CheckCircle2, Clock3, Database, ExternalLink, HeartPulse } from "lucide-react";
import Link from "next/link";
import { ActionableError } from "@/components/ui/ActionableError";
import { OzonModuleHeader } from "./OzonModuleHeader";
import { EmptyState, Freshness, MetricCard, OzonError, OzonLoading, OzonStaleNotice, StatusPill, formatDateTime, formatNumber } from "./OzonUi";
import { useOzonCockpit } from "./useOzonCockpit";

interface CabinetHealth { id: string; name: string; clientId: string; sellerApi: boolean; performanceConfigured: boolean; performanceApi: boolean; adUpdatedAt: string | null; adAgeHours: number | null; adCacheStatus: "ok" | "warning" | "error"; status: "ok" | "warning" | "error"; issues: string[] }
interface HealthData { generatedAt: string; scope: { label: string; count: number }; summary: { total: number; healthy: number; warnings: number; errors: number; performance: number; sync: "ok" | "warning" | "error" }; cabinets: CabinetHealth[]; latestSync: { status?: string; rows_affected?: number; error?: string | null; started_at?: string } | null }

export function OzonHealthPage() {
  const { data, loading, error, updating, refresh, reload } = useOzonCockpit<HealthData>("health", 14);
  return <div><OzonModuleHeader eyebrow="Ozon · Контроль" title="Здоровье интеграций" subtitle="Seller API, Performance API, свежесть рекламного кэша и последний запуск синхронизации для каждого кабинета." onRefresh={refresh} refreshing={loading} />
    <div className={`mx-auto max-w-[1600px] space-y-4 px-4 py-4 transition-opacity sm:px-5 ${updating ? "opacity-60" : ""}`}>{loading && !data ? <OzonLoading rows={6} /> : error && !data ? <OzonError message={error} onRetry={reload} /> : !data ? <EmptyState title="Нет кабинетов Ozon" detail="Добавьте кабинет и ключи API." href="/cabinets" /> : <>
      <div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs font-semibold text-slate-600">{data.scope.label}</div><Freshness generatedAt={data.generatedAt} label="Проверено" /></div>{error ? <OzonStaleNotice message={error} onRetry={reload} /> : null}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><MetricCard label="Кабинетов" value={formatNumber(data.summary.total)} /><MetricCard label="Кабинеты в норме" value={formatNumber(data.summary.healthy)} tone={data.summary.healthy === data.summary.total ? "emerald" : "amber"} /><MetricCard label="Предупреждения системы" value={formatNumber(data.summary.warnings)} tone={data.summary.warnings ? "amber" : "emerald"} /><MetricCard label="Ошибки системы" value={formatNumber(data.summary.errors)} tone={data.summary.errors ? "red" : "emerald"} /><MetricCard label="Performance работает" value={`${formatNumber(data.summary.performance)} / ${formatNumber(data.summary.total)}`} /></div>
      <div className="grid gap-4 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,0.6fr)]"><section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-4 py-3"><h2 className="text-sm font-bold text-slate-900">Кабинеты</h2><p className="mt-0.5 text-[10px] text-slate-400">Проверка доступности не раскрывает ключи и токены.</p></div><div className="divide-y divide-slate-100">{data.cabinets.map((cabinet) => <article key={cabinet.id} className="p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-sky-50 text-sky-700"><HeartPulse className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold text-slate-900">{cabinet.name}</h3><StatusPill status={cabinet.status} /></div><div className="mt-1 text-[10px] text-slate-400">Client ID {cabinet.clientId}</div><div className="mt-3 grid gap-2 sm:grid-cols-3"><Check label="Seller API" status={cabinet.sellerApi ? "ok" : "error"} detail={cabinet.sellerApi ? "Отвечает" : "Ошибка"} /><Check label="Performance API" status={!cabinet.performanceConfigured ? "warning" : cabinet.performanceApi ? "ok" : "error"} detail={!cabinet.performanceConfigured ? "Не подключён" : cabinet.performanceApi ? "Отвечает" : "Ошибка"} /><Check label="Рекламный кэш" status={cabinet.adCacheStatus} detail={cabinet.adUpdatedAt ? formatDateTime(cabinet.adUpdatedAt) : "Нет данных"} /></div>{cabinet.issues.length > 0 && <ul className="mt-3 list-disc space-y-1 pl-4 text-[10px] text-amber-700">{cabinet.issues.map((issue, index) => <li key={`${issue}-${index}`}>{issue}</li>)}</ul>}</div></div></article>)}</div></section>
        <aside className="space-y-4"><section className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2"><Database className="h-4 w-4 text-sky-600" /><h2 className="text-sm font-bold text-slate-900">Последняя синхронизация рекламы</h2></div><p className="mt-1 text-[10px] text-slate-400">Общий запуск по всем кабинетам Ozon, а не только по выбранному: за один заход крон берёт один кабинет.</p>{data.latestSync ? <div className="mt-4 space-y-3"><div className="flex items-center justify-between text-xs"><span className="text-slate-500">Статус</span><StatusPill status={data.summary.sync} /></div><div className="flex items-center justify-between text-xs"><span className="text-slate-500">Строк обновлено</span><span className="font-semibold tabular-nums">{formatNumber(Number(data.latestSync.rows_affected ?? 0))}</span></div><div className="flex items-center justify-between text-xs"><span className="text-slate-500">Запуск</span><span className="font-semibold">{formatDateTime(data.latestSync.started_at)}</span></div>{data.latestSync.error ? <ActionableError message={data.latestSync.error} label="Ozon реклама" compact tone={data.summary.sync === "error" ? "rose" : "amber"} /> : null}</div> : <div className="mt-4 text-xs text-slate-400">Запусков пока нет.</div>}<Link href="/sync" className="mt-4 inline-flex min-h-11 items-center gap-1.5 rounded-lg bg-sky-700 px-3 text-xs font-semibold text-white hover:bg-sky-800 sm:min-h-8">Открыть синхронизацию <ExternalLink className="h-3 w-3" /></Link></section><section className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-slate-400" /><h2 className="text-sm font-bold text-slate-900">Правила свежести</h2></div><ul className="mt-3 space-y-2 text-[11px] text-slate-500"><li>Seller API и Performance API опрашиваются при сборке этого снимка — время сборки указано выше как «Проверено».</li><li>Performance API проверяется выдачей токена.</li><li>Рекламное окно пересобирается раз в сутки: кэш старше 26 часов даёт предупреждение, старше 48 часов — ошибку.</li><li>Временный лимит/ожидание отчёта Ozon Performance считается предупреждением; настоящая ошибка последней синхронизации входит в общий счётчик ошибок.</li></ul><Link href="/cabinets" className="mt-3 inline-flex min-h-11 items-center text-xs font-semibold text-sky-700 sm:min-h-8">Настроить кабинеты <ExternalLink className="ml-1 h-3 w-3" /></Link></section></aside>
      </div>
    </>}</div>
  </div>;
}

function Check({ label, status, detail }: { label: string; status: "ok" | "warning" | "error"; detail: string }) {
  const tone = status === "ok" ? "border-emerald-100 bg-emerald-50/60" : status === "error" ? "border-red-100 bg-red-50/60" : "border-amber-100 bg-amber-50/60";
  const icon = status === "ok" ? <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" /> : <Clock3 className={`h-3.5 w-3.5 ${status === "error" ? "text-red-600" : "text-amber-600"}`} />;
  return <div className={`rounded-lg border p-2.5 ${tone}`}><div className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 md:text-[10px]">{icon}{label}</div><div className="mt-1 text-xs text-slate-500 md:text-[10px]">{detail}</div></div>;
}
