import { readFileSync } from "node:fs";

let passed = 0;
let failed = 0;

function ok(cond: boolean, msg: string) {
  if (cond) passed += 1;
  else {
    failed += 1;
    console.error("FAIL", msg);
  }
}

const studio = readFileSync("public/inferno/studio.html", "utf8");

ok(/compact:true/.test(studio), "Studio starts in compact operator mode");
ok(/COMPACT_HIDDEN_SCREENS=new Set\(\["inspector","static","balances","learn"\]\)/.test(studio), "compact mode hides non-MVP screens from navigation");
ok(/function visibleScreens\(\)\{ return S\.compact \? SCREENS\.filter/.test(studio), "navigation is derived from visible screens");
ok(/visibleScreens\(\)\.forEach/.test(studio), "renderNav uses compact-aware screen list");
ok(!/href=["'][^"']*patrick/.test(studio) && !/\{id:"text"/.test(studio) && /if\(s\.screen==="text"\)s\.screen="center";/.test(studio), "legacy patrick/text entry points stay hidden from Studio navigation without deleting files");
ok(/\{id:"worker",grp:"⚙ Система",chip:"08",tt:"Пульс завода",st:"живые прогоны"\}/.test(studio), "system navigation names the worker screen as factory pulse instead of infra jargon");
ok(/завод коротких роликов/.test(studio) && !/viral video graph/.test(studio), "rail branding stays in Russian operator language");
ok(/\{id:"compete",grp:"Старт",chip:"02",tt:"Анализ конкурентов",st:"разведка · разбор"\}/.test(studio) && !/разведка · decompose/.test(studio), "competitor analysis navigation avoids raw decompose jargon");
ok(!/if\(gens\|\|otk\|\|signalBits\.length\)/.test(studio) && !/"sprint 1 · fail-open"/.test(studio), "factory pulse stays compact in both command modes");
ok(!/box\.appendChild\(el\("button",\{class:"btn sm",style:"margin-top:8px;width:100%;justify-content:center;",onclick:\(\)=>go\("worker"\)\},"Worker"\)\)/.test(studio), "compact sidebar pulse does not duplicate Worker entry point");
ok(/function renderObservabilityCard\(host\)\{[\s\S]*if\(S\.compact\)return;/.test(studio), "execution observability is hidden from compact command center");
ok(/if\(heartbeatDiag&&!S\.compact\)/.test(studio), "heartbeat diagnostics are full-mode only");
ok(/пульс не настроен/.test(studio), "queue fallback pulse copy avoids saying the worker is dead");
ok(/renderToken:0/.test(studio) && /const token=\+\+S\.renderToken/.test(studio) && /const live=\(\)=>S\.screen==="center"&&S\.renderToken===token/.test(studio), "command center ignores stale async render passes");
ok(/async function screenWorker\(root, force, renderToken\)\{[\s\S]*const isLiveRender=\(\)=>S\.screen==="worker"&&S\.renderToken===token/.test(studio), "worker screen ignores stale async render passes");
ok(/const factorySuggested=suggested\.filter\(\(a\)=>!isWorkerInfraAction\(a&&a\.action\)\)/.test(studio), "worker screen filters infra-only suggested actions out of factory todo list");
ok(/const focusRun=orderedRuns\[0\]\|\|null;/.test(studio) && /focusRunLabel=focusRun\?\(focusRun\.stale\|\|focusRun\.status==="running"\?"Текущий прогон":"Последний прогон"\):"Прогон";/.test(studio), "worker screen focuses the top card on real factory runs instead of markdown task queue items");
ok(/const recentRuns=Array\.isArray\(runObservability&&runObservability\.recent_runs\)\?runObservability\.recent_runs:\[\];/.test(studio) && /"Очередь прогонов"/.test(studio), "worker screen shows real factory runs from observability instead of a fake task queue");
ok(/async function startProductionRun\(recipeId, opts\)/.test(studio) && /api\("\/graph-run",\{method:"POST"/.test(studio) && /"запустить снова"/.test(studio) && /"MP4"/.test(studio), "worker run control uses existing graph-run and exposes graph, restart, and MP4 actions");
ok(/focusRunArticle=focusRun&&focusRun\.article/.test(studio) && /r&&r\.output_url\?el\("button",\{class:"btn sm",onclick:\(\)=>openMedia\(r\.output_url,\{video:true\}\)\},"MP4"\)/.test(studio), "worker run queue includes operator-facing article and output video controls");
ok(/const activeRuns=recentRuns\.filter\(\(r\)=>r&&\(r\.active\|\|r\.status==="running"\|\|r\.stale\)\);[\s\S]*const queueRuns=\(activeRuns\.length\?activeRuns:recentRuns\);[\s\S]*const orderedRuns=\[\.\.\.queueRuns\][\s\S]*const visibleRuns=orderedRuns\.slice\(0,S\.compact\?4:8\)/.test(studio), "worker run queue prefers active runs while keeping a compact fallback");
ok(/focusRun\.active_step\?`идёт шаг \$\{runStepLabel\(focusRun\.active_step\)\}`:focusRun\.last_step\?`последний шаг \$\{runStepLabel\(focusRun\.last_step\)\}`:"прогон в работе"/.test(studio) && /focusRun\.active_step\?`застрял на шаге \$\{runStepLabel\(focusRun\.active_step\)\}`:focusRun\.last_step\?`застрял после шага \$\{runStepLabel\(focusRun\.last_step\)\}`:"прогон завис в работе"/.test(studio), "worker focus card explains live or stuck run progress instead of raw backlog tasks");
ok(/function heartbeatIssueLabel\(issue\)\{[\s\S]*table_missing:"таблица не поднята"[\s\S]*sender_missing:"передатчик пульса не запущен"[\s\S]*permission_denied:"нет доступа"/.test(studio) && /function errorCategoryLabel\(category\)\{[\s\S]*code==="other"\) return "без категории";/.test(studio), "worker screens map backend issue codes to operator-facing labels");
ok(/const sourceLabel=workerSource==="heartbeat_db"\?"таблица":"резерв";/.test(studio) && !/infra note:/.test(studio) && /"пульс потерян"/.test(studio), "worker status copy stays human and hides infra-note fallback text");
ok(/"сигнал: ",el\("b",\{style:"color:var\(--tx-hi\);"\},worker&&worker\.last_seen\?fmtWhen\(worker\.last_seen\):"—"\)/.test(studio) && /" · тишина: "/.test(studio) && /" · режим: "/.test(studio), "worker heartbeat card uses operator-facing labels instead of mixed English telemetry copy");
ok(/state==="alive" \? \{c:"var\(--ok\)", bg:"var\(--ok-bg\)", label:"на связи"\}/.test(studio) && /running:\{c:"var\(--acc-lt\)", bg:"var\(--vio-bg\)", label:"идёт"\}/.test(studio) && /warning:\{c:"var\(--warn\)", bg:"var\(--warn-bg\)", label:"предупр\."\}/.test(studio) && /run_fail:\{c:"var\(--err\)", bg:"var\(--err-bg\)", label:"сбой"\}/.test(studio), "worker status chips use product copy instead of raw backend enums");
ok(/"подвис", Number\(runObservability&&runObservability\.stale_running\|\|0\), "var\(--warn-bg\)"/.test(studio) && /r&&r\.stale\?"stale_running":r\.status/.test(studio), "worker run queue surfaces stale running runs separately");
ok(/"в выборке", Number\(runObservability&&runObservability\.active_sample_runs\|\|queueRuns\.length\|\|0\), "var\(--bg-input\)"/.test(studio) && /"архив", Number\(runObservability&&\(\(runObservability\.legacy_failed_runs\|\|0\)\+\(runObservability\.legacy_warning_runs\|\|0\)\)\|\|0\), "var\(--bg-input\)"/.test(studio), "worker queue meta distinguishes live sample runs from archived noise without task jargon");
ok(/сейчас живых инцидентов нет, но в архивном окне ещё лежит/.test(studio) && /"Разбор прогонов"/.test(studio), "full observability card explains historical-only incidents in operator language");
ok(!/if\(workerRow&&!S\.compact\)/.test(studio), "command center does not render a duplicate worker summary card");
ok(/class:"system-pill"[\s\S]*onclick:\(\)=>go\("worker"\)/.test(studio), "command center uses one compact system pill for ops and worker status");
ok(/hasCriticalSystemAlert=level==="critical"\|\|opsAlerts\.some/.test(studio) && /class:"card health-banner "/.test(studio), "factory health banner only surfaces critical system alerts in command center");
ok(!/задача "\+workerRow\.current_task_id/.test(studio) && /Идёт в фоне как серия прогонов\./.test(studio), "command center hides raw worker task ids and uses run-centric autopilot copy");
ok(/label:"идут прогоны"/.test(studio) && /label:"есть сбои"/.test(studio) && !/самопочинка срабатывала/.test(studio), "factory pulse uses plain run-state language instead of self-heal jargon");
ok(!/history "\+String\(stressHistory\.total_reports/.test(studio) && !/stability streak/.test(studio) && /opsAlerts\.slice\(0,3\)/.test(studio), "health banner avoids becoming a secondary observability dashboard");
ok(/"Пульс: "\+opsTone\.label\.toLowerCase\(\)/.test(studio) && /const statusTitle=level==="critical"\?"Нужна проверка":level==="degraded"\?"Есть риск":level==="healthy"\?"Система в норме":"Статус неясен";/.test(studio) && /details\.appendChild\(el\("summary",\{\},"Что проверить"\)\)/.test(studio), "command center health summary stays compact and product-facing");
ok(/header\("Пульс завода","пульс · прогоны · контроль"/.test(studio) && /loadingCard\("смотрю пульс и живые прогоны…"\)/.test(studio) && /const heartbeatSummary=heartbeatDiag\.issue==="table_missing"[\s\S]*таблица пульса ещё не поднята[\s\S]*резервный снимок и не блокирует прогоны/.test(studio) && /heartbeatIssueLabel\(heartbeatDiag\.issue\)/.test(studio) && /"Следом: "/.test(studio), "worker heartbeat diagnostics stay compact and explain the factory impact first");
ok(/function suggestedActionLabel\(action\)\{[\s\S]*inspect_stuck_runs:"разобрать подвисшие прогоны"[\s\S]*inspect_render_path:"проверить путь рендера"[\s\S]*inspect_claude_upstream:"проверить ответ Claude"[\s\S]*inspect_video_critic_structured_output:"проверить формат ответа видео-критика"[\s\S]*continue_monitoring:"продолжать наблюдение"/.test(studio) && /"Что проверить сейчас"/.test(studio) && /" пунктов"/.test(studio), "worker todo card turns backend actions into operator-facing tasks");
ok(/"Стресс 10\/10"/.test(studio) && /"прогонов "\+String\(lsCompleted\)\+"\/"\+String\(lsTotal\)/.test(studio) && /Последний stress-run закрыл 10\/10\./.test(studio) && /Stress-run не проверил завод: нужна авторизация\/CRON_SECRET\./.test(studio) && /"По базе: "\+String\(lsStability\.failure_diagnostics\.issue\)/.test(studio) && /архив: /.test(studio) && !/"История стресс-тестов"/.test(studio), "worker stress surface separates run KPI, auth blockers, and DB history");
ok(/"Сигнал качества"/.test(studio) && /"категории сбоев"/.test(studio) && /"категории предупреждений"/.test(studio) && /"верхние предупреждения"/.test(studio) && /"живые инциденты"/.test(studio) && /"тренд по часам"/.test(studio) && /"модель "\+String\(quality\.model_runs\|\|0\)/.test(studio) && /"текст "\+String\(quality\.text_runs\|\|0\)/.test(studio), "full observability sections are labeled in consistent Russian product language");
ok(/Если пульс уйдёт в `молчит` или `потерян`/.test(studio) && /проверять передатчик пульса/.test(studio) && /"пульс "\+heartbeatIssueLabel\(heartbeatDiag\.issue\|\|heartbeatDiag\.title\|\|"unknown"\)/.test(studio) && /"всего "\+\(p\.total\|\|0\)\+" · ок "\+\(p\.passed\|\|0\)\+" · предупр\. "\+\(p\.warning\|\|0\)\+" · сбой "\+\(p\.failed\|\|0\)/.test(studio) && /чинить путь пульса/.test(studio) && /errorCategoryLabel\(r\.error_category\)/.test(studio), "assistant guidance and observability summaries use the same operator vocabulary");
ok(/"предупреждения · выпуск не заблокирован"/.test(studio) && /"идёт "\+runStepLabel\(summary\.active_step\)/.test(studio) && /st==="done"\?"готово":st==="warning"\?"предупр\.":"сбой"/.test(studio), "OTK panel uses operator-facing labels for warnings, step summary, and execution statuses");
ok(/"шаги прогона"/.test(studio) && /"хвост "\+execLog\.length/.test(studio) && /st==="done"\?"готово":st==="warning"\?"предупр\.":"сбой"/.test(studio) && /runStepLabel\(e\.step\|\|""\)/.test(studio) && /"вход "\+inp/.test(studio) && /" · выход "\+out/.test(studio), "OTK execution log stays readable in product language");
ok(/function renderOpsFetchFallback\(host,errorText,stale\)\{[\s\S]*"Пульс временно недоступен"[\s\S]*stale[\s\S]*"не удалось подтянуть свежий снимок, поэтому оставляю на экране последний удачный статус\."[\s\S]*"не удалось подтянуть сводку завода, поэтому экран пока не может собрать статус\."/.test(studio) && /const prevWorkerState=S\.workerState&&!S\.workerState\.error\?S\.workerState:null;/.test(studio) && /if\(!state\)\{[\s\S]*renderOpsFetchFallback\(wrap,d&&d\.error,false\)/.test(studio), "worker screen stays fail-open when /ops fetch breaks and reuses the last good snapshot");
ok(/@media \(max-width:700px\)\{[\s\S]*\.hdr\{display:grid;grid-template-columns:1fr/.test(studio), "mobile command header stacks actions without horizontal overflow");
ok(/@media \(max-width:900px\)\{[\s\S]*\.rail-head>\.logo\{display:flex!important;\}[\s\S]*\.rail-head>div:not\(\.logo\),\.nav-cap,.nav-tt,.nav-st,.rail-foot\{display:none!important;\}/.test(studio), "mobile rail keeps only compact navigation chrome visible");
ok(/class:"niche-grid",role:"listbox"/.test(studio) && /grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/.test(studio), "niche selector uses stable 2x2 grid in normal desktop width");
ok(/role:"option","aria-selected":active\?"true":"false"/.test(studio), "niche tiles expose selected state semantically");
ok(/class:"filter-row",role:"group","aria-label":"Фильтр товаров"/.test(studio), "product filters are grouped and expose pressed state");
ok(!/n\.videos\+"\sвиральных"/.test(studio) && /шаблонов/.test(studio) && /товаров · "\+\(n\.videos\|\|0\)\+" роликов/.test(studio), "niche tiles keep only the useful counts and avoid duplicate virality chips");
ok(/class:"product-gap-chip"/.test(studio) && /data-real-frames/.test(studio) && !/есть winner/.test(studio) && !/Данные по товару:/.test(studio) && /Не хватает: /.test(studio) && /сигналы есть/.test(studio), "product cards stay compact and avoid backend-English status copy");
ok(/function splitBriefText/.test(studio) && /class:"rec-list"/.test(studio), "marketer panel uses scannable summary and recommendation cards");
ok(/"Развернуть бриф"/.test(studio) && /viral_examples\.slice\(0,2\)/.test(studio) && /content_recommendations\.slice\(0,3\)/.test(studio), "marketer panel keeps the right rail compact instead of expanding into a wall of examples");
ok(/header\("Статика","пины · карточки · лента"/.test(studio) && /const FORMATS=\[\["card_3x4","Карточка WB 3:4"\],\["pin_2x3","Пин 2:3"\],\["ig_4x5","Лента 4:5"\]\]/.test(studio) && /chip\("Охват",f\.objective==="reach"/.test(studio) && /chip\("Сохранения",f\.objective==="saves"/.test(studio) && /"Локальный рендер статики\. Канон: docs\/factory-pin-canon\.md"/.test(studio), "static generation screen uses operator-facing labels instead of English render jargon");
ok(/header\("Анализ конкурентов","разбор · "\+nicheLabel\(S\.activeNiche\)/.test(studio) && !/header\("Анализ конкурентов","decompose · /.test(studio) && /индекс "\+\(v\.virality_score\?Number\(v\.virality_score\)\.toFixed\(0\):"\?"\)/.test(studio) && /"Формат: "\+formatLabel\(v\.format_detected\)/.test(studio) && /\(v\.platform\|\|"TikTok"\)\+" · "\+formatLabel\(v\.format_detected\)/.test(studio), "competitor analysis screen uses Russian headers, virality labels, and format labels");
ok(/function runStepLabel\(value\)\{[\s\S]*"render-submit":"отправка в рендер"[\s\S]*"render-poll":"ожидание рендера"[\s\S]*"render-done":"рендер готов"[\s\S]*failed:"сбой"/.test(studio) && /"идёт "\+runStepLabel\(summary\.active_step\)/.test(studio) && /"последний "\+runStepLabel\(summary\.last_step\)/.test(studio) && /runStepLabel\(e\.step\|\|""\)/.test(studio), "operator surfaces translate raw run step codes into readable Russian labels");
ok(/function nodeTypeLabel\(value\)\{[\s\S]*hook_ugc:"UGC-хук"[\s\S]*before_after:"До\/после"[\s\S]*captions:"Титры"[\s\S]*static_post:"Статика"/.test(studio) && /function trackLabel\(value\)\{[\s\S]*video:"Видео"[\s\S]*captions:"Титры"/.test(studio) && /nodeTypeLabel\(n\.node_type\|\|n\.slot\)/.test(studio) && /trackLabel\(name\)/.test(studio) && /nodeTypeLabel\(sel\.node_type\|\|sel\.slot\)/.test(studio) && /runStepLabel\(c\.run\.step\|\|""\)/.test(studio), "canvas, timeline, OTK rows, and assistant context avoid raw node and step codes");
ok(/const learnWarnings=Array\.isArray\(d\.warnings\)\?d\.warnings\.filter\(Boolean\):\[\];[\s\S]*"предупреждения чтения"/.test(studio), "learn screen surfaces warning metadata instead of silently flattening degraded reads");
ok(/const ms=d\.market_summary\|\|null;[\s\S]*"Рынок после публикации"[\s\S]*"роликов с метриками"[\s\S]*"удержание"[\s\S]*"CTR карточки"[\s\S]*"ОТК vs рынок"[\s\S]*"топ по просмотрам"/.test(studio), "learn screen surfaces real market feedback without enabling auto-scaling");
ok(/const EVENT_LABEL=\{hook_chosen:"🏆 выбран хук",approved:"✓ одобрено",rejected:"✕ не то",generated:"⚙ собрано"/.test(studio) && /const ST=\{otk_pass:\["var\(--ok\)","ОТК ✓"\],approved:\["var\(--ok\)","одобрено"\],warning:\["var\(--warn\)","предупр\."\],otk_fail:\["var\(--warn\)","низкий ОТК"\],rejected:\["var\(--err\)","отклонено"\],artifact_fail:\["var\(--err\)","артефакт"\][\s\S]*generated:\["var\(--tx-bd\)","собрано"\]/.test(studio), "learn generation history uses explicit localized status labels instead of raw backend words");
ok(/const lineageBits=\[[\s\S]*r\.recipe_id!=null\?\("#"\+String\(r\.recipe_id\)\):null,[\s\S]*r\.attempt!=null\?\("попытка "\+String\(r\.attempt\)\):null,[\s\S]*r\.variant_idx!=null\?\("вариант "\+String\(r\.variant_idx\)\):null/.test(studio) && /reasonText=r\.reason\?String\(r\.reason\)\.slice\(0,72\):""/.test(studio), "learn generation history shows lineage bits and reason text for recent attempts");
ok(/function recipeStatusLabel\(status\)\{[\s\S]*warning:"предупр\."[\s\S]*running:"идёт"/.test(studio) && /const label=\{done:"готово",error:"сбой",submitted:"отправлено",pending:"ожидает",skip:"пропуск"\}/.test(studio) && /"в банк — победитель ✓/.test(studio) && /"✓ рынок → хук в победители"/.test(studio) && /"нужна перепроверка"/.test(studio) && /"каталог: "/.test(studio) && /"прогон"/.test(studio) && /"шаги "\+r\.execution_log_count/.test(studio) && /`рецепт #\$\{recipeId\}`/.test(studio) && /function recipeBuiltByLabel\(value\)\{[\s\S]*manual:"ручной"[\s\S]*assisted:"с подсказкой"[\s\S]*auto:"авто"/.test(studio) && /const recipeMeta=\[nicheLabel\(r\.niche\), formatLabel\(r\.format_detected\|\|r\.format\|\|r\.mode\), recipeBuiltByLabel\(r\.built_by\)\]\.filter\(Boolean\)\.join\(" · "\)/.test(studio) && /recipeStatusLabel\(shownStatus\)[\s\S]*runStepLabel\(r\.step\)/.test(studio), "library and operator toasts use product-facing recipe and winner language");
ok(/const isRunningRecipe=r\.status==="running"&&r\.step!=="done"&&r\.step!=="failed";/.test(studio) && /startProductionRun\(r\.id,\{restart:r\.status==="run_fail"\|\|r\.status==="warning"\}\)/.test(studio) && /openMedia\(r\.output_url,\{video:true\}\)\},"MP4"/.test(studio) && /go\("worker"\)\},"пульс"/.test(studio), "library recipe cards expose production controls without double-starting running recipes");
ok(/function estimateRecipeCost\(nodes\)\{[\s\S]*toolPriceAmount\(tool\)[\s\S]*Shotstack \(сборка\)[\s\S]*worst:total\*3/.test(studio), "run launch uses one recipe-node cost estimate with an OTK regen ceiling");
ok(/function lowBalanceLabelsFromState\(state\)\{[\s\S]*balances&&balances\.services[\s\S]*balances&&balances\.low/.test(studio), "budget guard derives low-balance labels from the ops snapshot");
ok(/async function canStartRunWithBudget\(recipeId\)\{[\s\S]*ensureOpsForBudget\(\)[\s\S]*openRecipe\(recipeId\)[\s\S]*запуск остановлен[\s\S]*смета прогона/.test(studio), "budget guard blocks graph-run only when ops reports low balances and otherwise shows a cost estimate");
ok(/async function startProductionRun\(recipeId, opts\)[\s\S]*if\(!\(await canStartRunWithBudget\(recipeId\)\)\)\{ delete S\.busyRun\[key\]; return; \}[\s\S]*api\("\/graph-run"/.test(studio), "library production start checks budget before POSTing graph-run");
ok(/async function startRun\(\)[\s\S]*const id=S\.recipe\.recipe\.id;[\s\S]*if\(!\(await canStartRunWithBudget\(id\)\)\)return;[\s\S]*api\("\/graph-run"/.test(studio), "assembly start checks budget before POSTing graph-run");
ok(/async function screenAssembly\(root\)[\s\S]*el\("button",\{class:"btn primary",onclick:\(\)=>startRun\(\)\}/.test(studio) && /const tl=el\("div",\{id:"timeline"\}\);[\s\S]*renderTimeline\(tl\);/.test(studio) && /автораскладка по длительности нод/.test(studio), "assembly screen shows a free timeline planning preview before the paid render starts");
ok(/async function takePreview\(n,p\)\{[\s\S]*n\.params\.preview_url=p\.url;[\s\S]*n\.params\.preview_hash=p\.hash;[\s\S]*await saveNode\(n\);[\s\S]*сборка не платит заново/.test(studio), "accepted node previews are persisted immediately before graph-run can start");
ok(/run\.run_id\?el\("div",\{class:"mono",style:"font-size:10px;color:var\(--tx-lo2\);"\},"прогон "\+run\.run_id\):null/.test(studio) && /function fmtMs\(ms\)\{[\s\S]*if\(sec<60\)return sec\+"с";[\s\S]*return min\+"м"\+\(rem\?" "\+rem\+"с":"\"\);/.test(studio) && /"авто — опрос сейчас/.test(studio) && /const srcLabel=\{api:"авто",manual:"ручной",estimated:"оценка"\}/.test(studio), "durations, run ids, and balances screen stay in Russian operator language");
ok(/closeFork=\(\)=>\{ ov\.remove\(\); document\.removeEventListener\("keydown",onForkKey\); \}/.test(studio) && /"Собрать контент"[\s\S]*"Закрыть"/.test(studio), "product format modal has an explicit close path");
ok(/closeNight=\(\)=>\{ ov\.remove\(\); document\.removeEventListener\("keydown",onNightKey\); \}/.test(studio) && /closeBrand=\(\)=>\{ ov\.remove\(\); document\.removeEventListener\("keydown",onBrandKey\); \}/.test(studio), "command center modals clean up Escape handlers");
ok(/closeEmbed=\(\)=>\{ ov\.remove\(\); document\.removeEventListener\("keydown",onEmbedKey\); \}/.test(studio) && /closeMedia=\(\)=>\{ ov\.remove\(\); document\.removeEventListener\("keydown",onMediaKey\); \}/.test(studio), "media modals clean up Escape handlers");
ok(/closeAuto=\(\)=>\{ ov\.remove\(\); document\.removeEventListener\("keydown",onAutoKey\); \}/.test(studio), "autofill result modal cleans up Escape handler");
ok(/if\(S\.compact\)\{[\s\S]*localStorage\.setItem\("noda_compact","0"\)/.test(studio), "assistant entry point expands full mode when needed");

if (failed) process.exit(1);
console.log(`studioSimplification: ${passed} passed, ${failed} failed`);
